name: Java CI with Maven

# Kích hoạt workflow khi có push hoặc pull_request
on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout mã nguồn
      uses: actions/checkout@v4

    - name: Thiết lập JDK 11 (Môi trường Java)
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    # Thực thi vòng đời build của Maven: test và package
    - name: Build dự án với Maven (Test & Package)
      run: mvn clean test package

    # Triển khai action upload-artifact để lưu file .jar
    - name: Upload file JAR lên Artifact
      uses: actions/upload-artifact@v4
      with:
        name: banksystem-jar
        path: target/*.jar