name: Java CI with Maven

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout mã nguồn
      uses: actions/checkout@v4

    - name: Thiết lập JDK 11 (Môi trường Java)
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    # BẮT BUỘC PHẢI CÓ DÒNG NÀY ĐỂ MAVEN CHUI VÀO ĐÚNG THƯ MỤC
    - name: Build dự án với Maven (Test & Package)
      working-directory: ./BankSystem
      run: mvn clean test package

    - name: Upload file JAR lên Artifact
      uses: actions/upload-artifact@v4
      with:
        name: banksystem-jar
        path: BankSystem/target/*.jar